[hyperparameters]
num_games = 30
iterations = 1600
c_puct = 1.0
epsilon = 0.25
num_test_games = 50
test_threshold = 0.5
threads = 8
searches_per_eval = 16
learning_rate = 0.01
batch_size = 2048
epochs = 1
num_old_gens = 1
name = "test"
cwd = "./logs"
num_logged = 30