[hyperparameters]
num_games = 2000
iterations = 400
c_puct = 3.0
epsilon = 0.25
num_test_games = 100
test_threshold = 0.5
threads = 8
searches_per_eval = 16
learning_rate = 0.01
batch_size = 2048
epochs = 10
anneal_factor = 0.5
patience = 3
num_old_gens = 1
name = "test"
cwd = "./logs"
num_logged = 10