[hyperparameters]
num_games = 25000
iterations = 1600
c_puct = 1.0
epsilon = 0.25
num_test_games = 1600
test_threshold = 0.52
threads = 0
searches_per_eval = 32
learning_rate = 0.01
batch_size = 2048
epochs = 1
num_old_gens = 3
name = "train"
cwd = "./logs"
num_logged = 10
