[hyperparameters]
num_games = 25000
iterations = 1600
c_puct = 3.0
epsilon = 0.25
num_test_games = 400
test_threshold = 0.55
threads = 0
searches_per_eval = 16
learning_rate = 0.01
batch_size = 2048
epochs = 10
anneal_factor = 0.5
patience = 5
num_old_gens = 2
name = "train"
cwd = "./logs"
num_logged = 10