[hyperparameters]
num_games = 10
max_searches = 16
c_puct = 3.0
epsilon = 0.25
num_test_games = 2
test_threshold = 0.5
num_threads = 1
searches_per_eval = 1
learning_rate = 0.001
batch_size = 2048
epochs = 10
anneal_factor = 0.5
patience = 2
num_old_gens = 2
name = "test"
cwd = "./logs"
num_logged = 10