#ifndef SOLVER_H
#define SOLVER_H

#include <cstdint>

#include <vector>

#include "game.h"

/// @brief Exact endgame solver: the game-theoretic result (win, draw or
/// loss for the side to move) by alpha-beta search to the end of the game
/// @details Scores are exact results in {-1, 0, 1}, so a transposition table
/// stores bounds on them and a search needs no depth limit: every move lowers
/// P = 2 * reserves + occupied spaces by at least one, so games end within P
/// plies and the search graph has no cycles. The number of positions visited
/// can be capped; a capped solve reports kUnknown.
/// Worklog 2026-09-25-nn-architectures, entry 08.
class Solver {
 public:
  /// @brief Four entries sharing one cache line; a store replaces the same
  /// position, else a stale entry, else the one with the smallest P (the
  /// cheapest to recompute). Entry 13.
  struct alignas(64) Bucket {
    uint64_t board[4];  // the four boards together: one AVX2 compare
    uint64_t meta[4];
  };

  /// @brief Returned when the node cap was reached before a result
  static constexpr int32_t kUnknown = 2;

  /// @param log2_entries The transposition table has 2^log2_entries entries
  explicit Solver(int32_t log2_entries = 20);

  /// @brief Solve a position
  /// @param max_nodes Give up after visiting this many positions
  /// @return 1, 0 or -1 for the side to move, or kUnknown
  int32_t solve(const Game &game, uint64_t max_nodes);

  /// @brief Positions visited by the last solve
  uint64_t nodes() const noexcept { return nodes_; }

  /// @brief Forget every stored result (constant time)
  void clear() noexcept;

 private:
  /// @param legal, lines The position's legal moves and whether a line
  /// stands, already generated by the caller
  int32_t search(const Game &game, const MoveMask &legal, bool lines,
                 int32_t alpha, int32_t beta);

  /// @brief A quiet move cut off: credit it in the history table
  void recordCutoff(uint64_t board, uint64_t rest, int32_t move);
  /// @brief Store a result with its bound and best move; returns best
  int32_t store(uint64_t board, uint64_t rest, int32_t best, int32_t alpha0,
                int32_t beta, int32_t best_move);

  enum Bound : int8_t { kExact = 0, kLower = 1, kUpper = 2 };
  /// @brief 16 bytes: the board word, and one word packing the rest of the
  /// key (side to move, 6 reserve counts in 3 bits each: bits 0-18), score
  /// + 1 (19-20), bound (21-22), best move + 1 (23-29; 0 for none), the
  /// position's horizon P (30-35) and the epoch (36-63; valid only when
  /// equal to epoch_). Entry 13.
  struct Entry {
    uint64_t board{0};
    uint64_t meta{0};
  };
  static constexpr uint32_t kEpochBits = 28;
  static_assert(sizeof(Entry) == 16);

  std::vector<Bucket> table_;
  uint64_t mask_;
  uint32_t epoch_{1};
  /// @brief History heuristic: per side to move and move, how much quiet
  /// cutoffs it produced this solve (weight P^2), to order quiet moves
  uint32_t history_[2][kNumMoves]{};
  uint64_t nodes_{0};
  uint64_t max_nodes_{0};
  bool aborted_{false};
};

#endif
