name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - corintho/cpp/src/trainmc.cpp
      - corintho/cpp/src/node.cpp
      - corintho/cpp/src/game.cpp
      - corintho/cpp/src/move.cpp
      - corintho/cpp/src/util.cpp
      - corintho/cpp/include/trainmc.h
      - corintho/cpp/include/node.h
      - corintho/cpp/include/game.h
      - corintho/cpp/include/move.h
      - corintho/cpp/include/util.h
      - corintho/docker/*
      - .github/workflows/docker.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/corintho-ai/corintho-play:latest

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.1
      with:
        project_id: corintho-ai
        service_account_key: ${{ secrets.GCR_JSON_KEY }}
        export_default_credentials: true
    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy corintho-play --image gcr.io/corintho-ai/corintho-play:latest --platform managed --region us-central1 --allow-unauthenticated
