name: Lint

on:
  push:
    paths:
      - 'corintho_ai/cpp/src/*.cpp'
      - 'corintho_ai/cpp/include/*.h'
      - '.github/workflows/run-lint-cpp.yaml'
  pull_request

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format
      run: sudo apt-get install -y clang-format-11
    - name: Check C++ formatting
      run: |
        find corintho_ai/cpp -name '*.h' -or -name '*.cpp' | xargs clang-format-11 -i --verbose
        git diff --exit-code
        find tests/cpp -name '*.h' -or -name '*.cpp' | xargs clang-format-11 -i --verbose
        git diff --exit-code